# Generated by Django 4.1.5 on 2023-01-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_messenger_phonenumber_messenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='passport',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
    ]
