# Generated by Django 4.1.5 on 2023-01-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_alter_customer_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='passport',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Паспорт'),
        ),
    ]
