# Generated by Django 4.1.5 on 2023-01-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Бак')),
                ('gross_volume', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Объем')),
                ('excluded_volume', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Объем')),
                ('volume', models.DecimalField(decimal_places=2, editable=False, max_digits=5, verbose_name='Полезный объем')),
                ('weld_length', models.IntegerField(verbose_name='Длина шва, см')),
                ('weight', models.DecimalField(decimal_places=1, help_text='Вес в килограммах', max_digits=3, verbose_name='Вес')),
                ('regular', models.BooleanField(db_index=True, verbose_name='Проверенный')),
            ],
            options={
                'verbose_name': 'Бак',
                'verbose_name_plural': 'Баки',
            },
        ),
    ]
