# Generated by Django 4.1.5 on 2023-01-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tank',
            name='volume',
        ),
        migrations.AlterField(
            model_name='tank',
            name='excluded_volume',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Исключаемый Объем'),
        ),
        migrations.AlterField(
            model_name='tank',
            name='gross_volume',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Общий Объем'),
        ),
    ]
