# Generated by Django 4.1.5 on 2023-01-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0002_remove_tank_volume_alter_tank_excluded_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='volume',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5, null=True, verbose_name='Полезный объем'),
        ),
    ]
