# Generated by Django 4.1.5 on 2023-01-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0003_tank_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='volume',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5, verbose_name='Полезный объем'),
        ),
    ]
