# Generated by Django 4.1.5 on 2023-01-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0005_alter_tank_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welding', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Цена за см шва, руб')),
                ('cut', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Цена за см реза, руб')),
                ('metal', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена кг металла, руб')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Константа',
                'verbose_name_plural': 'Константы',
            },
        ),
        migrations.AddField(
            model_name='tank',
            name='cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=7, null=True, verbose_name='Себестоимость, руб'),
        ),
        migrations.AddField(
            model_name='tank',
            name='cut_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=7, null=True, verbose_name='Раскрой, руб'),
        ),
        migrations.AddField(
            model_name='tank',
            name='metal_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=7, null=True, verbose_name='Металл, руб'),
        ),
        migrations.AddField(
            model_name='tank',
            name='price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=7, null=True, verbose_name='Цена, руб'),
        ),
        migrations.AddField(
            model_name='tank',
            name='welding_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=7, null=True, verbose_name='Сварка, руб'),
        ),
    ]
