# Generated by Django 4.1.5 on 2023-01-08 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0006_cost_tank_cost_tank_cut_cost_tank_metal_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cost',
            options={'ordering': ['-time_create'], 'verbose_name': 'Константа', 'verbose_name_plural': 'Константы'},
        ),
    ]
