# Generated by Django 4.1.5 on 2023-01-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0007_alter_cost_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='dut',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=5, verbose_name='Цена ДУТ ВАЗ, руб'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tank',
            name='difficult_koef',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Надбавка за сложность, руб'),
        ),
    ]
