# Generated by Django 4.1.5 on 2023-01-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0010_vehicletype_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='tank',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tanks',
            field=models.ManyToManyField(related_name='vehicles', to='tanks.tank', verbose_name='Наименование бака'),
        ),
    ]
