# Generated by Django 4.1.5 on 2023-01-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0011_remove_vehicle_tank_vehicle_tanks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='tanks',
            field=models.ManyToManyField(blank=True, related_name='vehicles', to='tanks.tank', verbose_name='Наименование бака'),
        ),
    ]
