# Generated by Django 4.1.5 on 2023-01-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0012_alter_vehicle_tanks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='tanks',
        ),
        migrations.AddField(
            model_name='tank',
            name='vehicles',
            field=models.ManyToManyField(blank=True, related_name='tanks', to='tanks.vehicle', verbose_name='Транспортное средство'),
        ),
    ]
