# Generated by Django 4.1.5 on 2023-01-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0013_remove_vehicle_tanks_tank_vehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tank',
            name='excluded_volume',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Объем стенок бака и перегородок', max_digits=5, verbose_name='Исключаемый Объем, л'),
        ),
        migrations.AlterField(
            model_name='tank',
            name='gross_volume',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Общий Объем, л'),
        ),
        migrations.AlterField(
            model_name='tank',
            name='volume',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5, null=True, verbose_name='Полезный объем, л'),
        ),
        migrations.AlterField(
            model_name='tank',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Вес, кг'),
        ),
    ]
