# Generated by Django 4.1.5 on 2023-01-10 18:41

from django.db import migrations, models
import tanks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0014_tank_description_alter_tank_excluded_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='sketch',
            field=models.ImageField(null=True, upload_to=tanks.models.get_path_for_sketches, verbose_name='Чертеж'),
        ),
    ]
