# Generated by Django 4.1.5 on 2023-02-06 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0016_alter_tank_sketch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tank',
            name='vehicles',
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tanks.vehicle', verbose_name='ТС')),
            ],
            options={
                'verbose_name': 'Модель Транспортного средства',
                'verbose_name_plural': 'Модель Транспортных средств',
            },
        ),
        migrations.AddField(
            model_name='tank',
            name='vehicles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tanks.vehicle', verbose_name='Транспортное средство'),
        ),
    ]
