# Generated by Django 4.1.5 on 2023-02-06 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0017_remove_tank_vehicles_vehiclemodel_tank_vehicles'),
    ]

    operations = [
        migrations.CreateModel(
            name='TankToVehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tanks.tank', verbose_name='Бак')),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tanks.vehiclemodel', verbose_name='Модель ТС')),
            ],
        ),
    ]
