# Generated by Django 4.1.5 on 2023-02-06 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0019_tanktovehiclemodel_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tanktovehiclemodel',
            name='vehicle',
        ),
    ]
