# Generated by Django 4.1.5 on 2023-02-06 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0021_tanktovehiclemodel_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TankToVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tanks.tank', verbose_name='Бак')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tanks.vehicle', verbose_name='ТС')),
            ],
            options={
                'verbose_name': 'ТС',
                'verbose_name_plural': 'ТС',
            },
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='TankToVehicleModel',
        ),
        migrations.DeleteModel(
            name='VehicleModel',
        ),
    ]
