# Generated by Django 4.1.5 on 2023-02-04 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0013_alter_city_options_alter_region_options'),
        ('tanks', '0016_alter_tank_sketch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Покупатель')),
                ('tank', models.ManyToManyField(to='tanks.tank', verbose_name='Бак')),
            ],
        ),
    ]
