# Generated by Django 4.1.5 on 2023-02-05 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderstatus_options_remove_order_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='TK')),
            ],
            options={
                'verbose_name': 'Транспортная компания',
                'verbose_name_plural': 'Транспортные компании',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.deliverycompany', verbose_name='ТК'),
        ),
    ]
