# Generated by Django 4.1.5 on 2023-02-05 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_deliverycompany_order_delivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverycompany',
            options={'ordering': ('name',), 'verbose_name': 'Транспортная компания', 'verbose_name_plural': 'Транспортные компании'},
        ),
        migrations.AlterField(
            model_name='deliverycompany',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.deliverycompany', verbose_name='Доставка'),
        ),
    ]
