# Generated by Django 4.1.5 on 2023-02-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_deliverycompany_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyorderstatus',
            name='status_date',
            field=models.DateTimeField(verbose_name='Время статуса'),
        ),
    ]
