# Generated by Django 4.1.5 on 2023-02-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_historyorderstatus_status_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyorderstatus',
            name='status_date',
            field=models.DateTimeField(verbose_name='Дата статуса'),
        ),
    ]
