# Generated by Django 4.1.5 on 2023-02-05 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_status_date_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 5, 19, 7, 52, 352413, tzinfo=datetime.timezone.utc), verbose_name='Дата изменения статуса'),
        ),
    ]
