# Generated by Django 4.1.5 on 2023-02-05 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_status_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата изменения статуса'),
        ),
    ]
