# Generated by Django 4.1.5 on 2023-02-05 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_alter_deliverycompany_options_and_more'),
        ('tanks', '0016_alter_tank_sketch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Статус бака',
                'verbose_name_plural': 'Статус баков',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productstatus', verbose_name='Статус')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tanks.tank', verbose_name='Бак')),
            ],
            options={
                'verbose_name': 'Статус бака',
                'verbose_name_plural': 'Статус баков',
            },
        ),
    ]
