# Generated by Django 4.1.5 on 2023-02-05 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Производство', 'verbose_name_plural': 'Производство'},
        ),
    ]
